title: "Glorified Studios Staff"
lang: "en-GB"
repository: GlorifiedStudios/Team
baseurl: "/"

collections:
  staff:
    order:
      - glorifiedpig.md
      - internet.md
    output: true
  teams:
    order:
      - development.md
      - board.md
      - moderation.md
    output: true

defaults:
  - scope:
      type: "staff"
      path: ""
    values:
      layout: "staff"
  - scope:
      type: "teams"
      path: ""
    values:
      layout: "team"

plugins:
  - kramdown
  - kramdown-parser-gfm
  - liquid
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-avatar
  - jekyll-remote-theme
  - jemoji
  - jekyll-mentions
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
